- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/data/within_subject.json
- nibabies/utils/misc.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/brain_extraction.py
- nibabies/workflows/base.py
Slightly more complicated than #18 due to the fact that the UNCInfant0-1-2 templates are not packaged with a T2w template.
This implementation uses a cross-modal registration between the participant's `T2w` image and the template (`T1w`). Then, within subject registration of the `T2w` to the `T1w` gets us the much improved mask in `T1w` space.
> FIX: Require T2w for brain extraction

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/brain_extraction.py
- nibabies/workflows/anatomical/preproc.py
- nibabies/workflows/anatomical/registration.py
Minimize validations, conformations and INU corrections, and gather them up together within
only one workflow for both T1w and T2w paths.
Also simplify the brain extraction and the co-registration workflows accordingly.
> ENH: Revise creation of anatomical templates

- nibabies/cli/parser.py
- nibabies/workflows/bold/registration.py
- Default to `mri_coreg` if FreeSurfer is available
- FSL FLIRT not ideal, but usable when FS not available
> FIX: T1 BOLD coregistration

- Dockerfile
Closes #44 
Infant FreeSurfer already packages `reg_aladin`
> FIX: Remove legacy installation of NiftyReg

- nibabies/interfaces/workbench.py
Preparation for #49 
Currently untested.
> ENH: CiftiDilate interface

- nibabies/utils/bids.py
Fixes #82
Grouping should not increase/decrease the number of BOLD files.
Conditions that modify combinations/files should be exclusive.
> FIX: Ensure BOLD file count is preserved

- nibabies/utils/patches.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/outputs.py
- setup.cfg
Closes #90 
This PR allows setting of `--output-spaces MNIInfant:cohort-x:res-y` and `UNCInfant:cohort-x`.
- `MNIInfant` removed from "res-less" templates
- The anatomical derivative workflow from smriprep was ported over, to allow for a change when calculating the default template resolution.
The final item to do before releasing is to cut a new smriprep release and update our minimum version.
> FIX: Standard output spaces

- .circleci/config.yml
- In cases where the Docker file changes drastically, this will speed up builds
- This will likely want to be changed in `maint/` branches to account for Dockerfile changes across versions
> CI: Attempt to pull most recent dev version

- nibabies/config.py
- nibabies/workflows/bold/registration.py
This addresses #97, switching the default BOLD -> T1w coregistration algorithm from `mri_coreg` to `FLIRT`.
> FIX: BOLD to template normalization

- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/confounds.py
- Adds ``--fd-radius`` flag to allow customizing FD radius (in mm)
- Sets the default value to 45 (changed from 50)
Closes #103
> ENH: Framewise displacement head radius flag

- Dockerfile
As we saw in nipreps/fmriprep#2535, this can help Singularity errors
> DOCKER: Strip ABI tag from libQt5Core.so.5

- wrapper/nibabies_wrapper.py
Closes #107 
- Use single quotes to appease existing `sed` version substitution on release
- Update python patches path
> MAINT: Wrapper fixes

- nibabies/__init__.py
To remove the pesky import warning
```
FutureWarning: Setting 'extension_initial_dot' will be removed in pybids 0.16.
warnings.warn("Setting 'extension_initial_dot' will be removed in pybids 0.16.",
```
> MAINT: Only alter pybids config in legacy versions

- nibabies/interfaces/freesurfer.py
Allows for >24 month processing.
Initial testing with 25/26 months showed reasonable results.
> ENH: Remove infant recon all age cap

- .github/workflows/style.yml
- nibabies/interfaces/confounds.py
- nibabies/interfaces/multiecho.py
- nibabies/interfaces/workbench.py
- pyproject.toml
- setup.cfg
I set `skip-string-normalization` just to avoid automatic formatters from making unnecessary changes and polluting PRs. Probably not relevant since you've already converted, so I can remove it if you prefer.
> STY/TEST: Set global style and doctest options

- .pre-commit-config.yaml
To avoid all the times where I forget to run `black` and then have to fix the commits.
> MAINT: Add pre-commit checks

- .circleci/config.yml
Forgetten adjustment after dd478567b6fcfd6e0b1f6d90c60a865987bd5ebc
> FIX: Remove excess arguments on wrapper tests

- nibabies/workflows/anatomical/base.py
Missed during the addition of the `--derivatives` flag, the precomputed aseg should be used within the call to `infant_recon_all`.
> FIX: Use precomputed aseg within `infant_recon_all`

- nibabies/config.py
With the current logic, an extra `MNIInfant:cohort-X` space may have been added to `SpatialReferences`, unnecessarily adding excessive processing time. This patch should ensure other `MNIInfant` space instances are not added if it is already present.
> FIX: Clean up default output space handling

- nibabies/config.py
- nibabies/data/tests/config.toml
- nibabies/tests/test_config.py
- wrapper/nibabies_wrapper.py
Initially meant as a port of updates from the fMRIPrep config, this PR sneaks in a few other things as well:
- Numpy random seed tracking
- Configuration module tests
- Pretty printing / loading for list of `pathlib.Path`s within the config module. `--derivatives` multi-paths were not being handled correctly.
- Docker wrapper patches path (missed in #191)
- Reference was not correctly specified (missed in #196)
> MAINT: Various configuration touch-ups

- nibabies/data/boilerplate.bib
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/segmentation.py
- nibabies/workflows/anatomical/surfaces.py
Fixes up boilerplate entries for anatomical segmentations / surfaces.
Adds bib entry for `infant_recon_all`
> FIX: Clean up generated boilerplate

- .pre-commit-config.yaml
- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/workflows/base.py
- Adds `--topup-max-vols` flag to control how many volumes are used with TOPUP.
- Enables susceptibility distortion correction in the case where single phase-encoding fieldmap is used to correct opposite phase-encoding BOLD/EPI runs.
Closes #204
> ENH: Improve fieldmap support

- .github/workflows/pytest.yml
- nibabies/cli/parser.py
- nibabies/cli/run.py
- nibabies/cli/workflow.py
- nibabies/config.py
- nibabies/reports/core.py
- nibabies/utils/bids.py
- nibabies/workflows/base.py
- setup.cfg
Closes #75, #147
This PR enables finer-grain session control. 
- Add a flag `-s/--session-id` to control session processing
- Refactor `sub-X.html` outputs into sub-X_ses-Y.html` to allow coexistence of multiple session reports. If no session information is provided, a `sub-X.html` is still produced.
> ENH: Treat session as first-class identifier

- nibabies/cli/parser.py
- nibabies/cli/run.py
- nibabies/cli/workflow.py
- nibabies/config.py
- Builds workflow / boilerplate within the same process, which will greatly simplify debugging. 
- Less warnings by default, but can be re-added setting the `NIBABIES_SHOW_WARNINGS` envvar to a true value.
- Set `OMP_NUM_THREADS` envvar to 1 when constructing the workflow. This has been shown to greatly reduce VMS (see nipreps/mriqc#984)
> RF/ENH: Rework workflow generation

- Dockerfile
- nibabies/workflows/anatomical/surfaces.py
- nibabies/workflows/bold/registration.py
Closes #222
Closes #97
Supersedes #171
This remedies the problem of incorrect anatomical to/from fsnative xforms. This is likely what we were seeing in #97, and by switching to the FSL BBR workflow, we were not using the `fsnative2anat_xfm` anymore.
> FIX: FSNative <-> anatomical transforms

- nibabies/interfaces/nibabel.py
- nibabies/interfaces/tests/test_nibabel.py
- nibabies/workflows/bold/resampling.py
Closes #228 
Adds a new interface `ReorientImage`, which should be ported to niworkflows, to handle reorientations. This interface is leveraged just before the CIFTI creation, to the subcortical volume and labels.
> ENH: Add interface for reorienting images

- long_description.md
- setup.cfg
> DOC: Add long description including background/significance

- nibabies/workflows/bold/resampling.py
Follows https://github.com/nipreps/fmriprep/pull/2879
> FIX: Remove cortex masking during vol2surf sampling

- .maint/update_changes.sh
- .maint/update_zenodo.py
- CHANGES.md
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/outputs.py
- output preprocessed T2w volume as "space-T1w_desc-preproc_T2w.nii.gz"
- If input includes T1w volume, T2w volume, and precomputed T1w mask, use SDCFlows brain extraction wf for T2w which avoids doing redundant brain extraction of T1w
> ENH: Add preprocessed T2w volume to outputs

- nibabies/workflows/base.py
- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/boldref.py
- nibabies/workflows/bold/stc.py
Closes #253 
This PR reverts bold reference generation to being calculated per run.
Included is a new workflow `init_infant_epi_reference_wf` that uses the following heuristic is used to generate the reference map:
1) Matching single-band reference to BOLD image
1) BOLD image (first 16 volumes dropped to avoid excessive motion if participant is startled)
> ENH: Runwise bold reference generation

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/segmentation.py
- Use MapLabels interface to remap FreeSurfer aseg labels to MCRIB format
- "anat_mcrib" volume added to outputnode of anat_segmentations_wf
> Remap labels from FreeSurfer aseg to MCRIB 

- Dockerfile
- nibabies/__about__.py
Since the [MIRTK container](https://github.com/nipreps-containers/mirtk) is built off jammy, we should bump up our Docker image. 
No FreeSurfer update yet, until we drop infant-recon-all.
> MNT: Upgrade Docker base, c3d

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/outputs.py
- nibabies/workflows/base.py
- pyproject.toml
Ports nipreps/smriprep#325 and nipreps/fmriprep#2959 to nibabies.
It doesn't look like we're resampling to fsLR in CircleCI, so this will require manual tests.
> ENH: Resample morphometrics to fsLR dscalar CIFTI-2 files if ``--cifti-output`` is used

- Dockerfile
- nibabies/cli/mcribs.py
- nibabies/interfaces/mcribs.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/segmentation.py
- pyproject.toml
This replaces the original MIRTK integration (#269) with MCRIBS, which seems to do a better job handling intersection errors.
> ENH: Testing MCRIBS integration 

- nibabies/interfaces/mcribs.py
This is a safeguard for various `cd <freesurfer-dir>` calls that MCRIBSReconAll can make.
> FIX: Create FreeSurfer directories

- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/data/boilerplate.bib
- nibabies/interfaces/mcribs.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/preproc.py
- nibabies/workflows/anatomical/surfaces.py
- nibabies/workflows/anatomical/template.py
- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/resampling.py
This PR adds a new workflow (`init_mcribs_surface_recon_wf`) that can be used as an alternative to `recon-all`/`infant_recon_all` to produce anatomical surfaces.
To use this workflow, the new flag `--surface-recon-method` needs to be used with the option `mcribs`.
With the addition of this new flag, the now redundant `--force-reconall` flag is deprecated.
Additionally, the infantFS surface workflow was renamed to better reflect which method is being used.
> ENH: Add M-CRIB-S surface processing

- nibabies/config.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/brain_extraction.py
- nibabies/workflows/anatomical/registration.py
These mislabeled connections were not detected because CI is using precomputed derivatives.
This catches a bug where session-less data's `session_id: None` was being coerced into a string during configuration writing/reading.
> FIX: Remove duplicated connections

- nibabies/workflows/bold/t2s.py
> ENH: Dilate BOLD mask by 2 voxels to prevent over-aggressive masking degrading T2* map estimation

- nibabies/workflows/bold/resampling.py
Restores medial wall masking of CIFTI surface BOLD timeseries (originally part of #212 ) and reorientation of CIFTI subcortical BOLD timeseries to LAS (#229 ); both fixes were unintentionally reverted when #278 was merged.
> FIX: restore cifti medial wall masking, subcortical volume LAS reorientation

- .circleci/bcp_anat_outputs.txt
- .circleci/bcp_full_outputs.txt
- .circleci/config.yml
- `sort` behavior seemingly changed with the newer circle images
- updated testing data derivatives formatting should now allow `--derivatives` pathway to be tested.
Continues #305
> CI: Fix output order

- nibabies/workflows/anatomical/base.py
Running `--surface-recon mcribs` with a derivative mask would cause the process to hang indefinitely.
> FIX: Connect derivatives mask to mcribs recon

- nibabies/cli/run.py
- nibabies/utils/telemetry.py
- pyproject.toml
- requirements.txt
Strips away error handling logic, which has been ported to `migas.track_exit` and lightens the server load
> chore: update to latest migas api

- nibabies/workflows/bold/resampling.py
Uses the boldmask2std xfm (instead of anat2std) to transform tedana t2star maps to standard space(s). 
Addresses https://github.com/nipreps/nibabies/issues/320 .
> Use correct xfm to resample tedana t2star map to std

- nibabies/cli/run.py
- nibabies/cli/workflow.py
- nibabies/data/reports-spec.yml
- nibabies/reports/core.py
- nibabies/workflows/anatomical/outputs.py
- pyproject.toml
Start using nireports, rather than the legacy reporting in niworkflows. This ensures each `<subject>-<session>.html` reports only includes reportlets relevant to that subject/session pairing.
Additionally, a unique reportlet is generated per surface reconstruction method.
> ENH: Use nireports report generation

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/template.py
> FIX: Multiple T2ws, coerce reference to string

- nibabies/workflows/anatomical/resampling.py
Change to use the fsLR reg sphere as "current sphere" for resampling MCRIBS morphometrics to fsLR, as is used for MCRIBS BOLD fsLR resampling.
> Use fsLR reg sphere for MCRIBS morphometrics resampling

- nibabies/cli/parser.py
> FIX: Catch nonexistent derivatives, clean up subworkflow logic

- .circleci/config.yml
- Removes `pyenv versions` parsing in favor of just defining MAJOR(.MINOR)
- Bumps Python convenience images
> FIX: Easier pyenv usage

- nibabies/workflows/bold/alignment.py
Closes #343.
Changes proposed:
- Replace outdated `resource_filename` calls with the new `load_data`.
> Replace `resource_filename` with `load_data`

- .maint/contributors.json
- nibabies/workflows/anatomical/base.py
Hello! 
I am doing some debugging of a script that runs `nibabies` and noticed I was getting the error shown below. This PR aims to add a more informative `RunTimeError` for users in the future.
```
Traceback (most recent call last):
File "/opt/conda/envs/nibabies/bin/nibabies", line 8, in <module>
sys.exit(main())
File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/run.py", line 59, in main
retval = build_workflow(config_file)
File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/cli/workflow.py", line 76, in build_workflow
retval["workflow"] = init_nibabies_wf(config.execution.unique_labels)
File "/opt/conda/envs/nibabies/lib/python3.10/site-packages/nibabies/workflows/base.py", line 130, in init_nibabies_wf
single_subject_wf = init_single_subject_wf( …
```
> FIX: Raise informative error if no t1w or t2w found

- nibabies/utils/bids.py
- nibabies/utils/tests/test_bids.py
Close #348 
Sorry for the delay on getting to this. Now calling an instance of the `Derivatives` class will return something like below. WDYT? 
```
Derivatives |
t2w_mask: None
t1w_mask: None
t1w_aseg: None
t2w_aseg: None
```
> ENH: better repr for Derivatives class

- nibabies/cli/run.py
- pyproject.toml
Popping up in the latest tests - this increases the minimum templateflow version and adds additional entities when retrieving the aparc dseg.
> FIX: Avoid retrieving multiple templates from latest TF

- nibabies/utils/misc.py
Per [nipype.pipeline.engine.utils.evaluate_connect_function](https://github.com/nipy/nipype/blob/4d1352ade7171fd5f55eff62cee4c99a4f9cfed1/nipype/pipeline/engine/utils.py#L687-L701):
```
def evaluate_connect_function(function_source, args, first_arg):
func = create_function_from_source(function_source)
try:
output_value = func(first_arg, *list(args))
except NameError as e:
if e.args[0].startswith("global name") and e.args[0].endswith("is not defined"):
e.args = (
e.args[0],
(
"Due to engine constraints all imports have to be done "
"inside each function definition"
),
)
raise e
return output_value
```
If I'm understanding this right I think we need to nest the `pathlib.Path` import within [fix_multi_source_name](https://github.com/nipreps/nibabies/blob/7b1e91d5d84094129caa29e16803f842605eaa …
> FIX: nest pathlib import in fix_multi_source_name

- nibabies/workflows/base.py
Closes #375 
It's a simple fix so figured I'd just do it, will work on getting CI passing now
> FIX: Do not require mniinfant xfm if no cifti

- nibabies/tests/test_config.py
- nibabies/workflows/base.py
Closes #380 
@madisoth I believe this should do the trick - running a local test now.
> FIX: Ensure 2mm template is added when running CIFTI

- .circleci/config.yml
- nibabies/utils/bids.py
- nibabies/utils/tests/test_bids.py
- Adds support for `weeks` and `years` age units while parsing, and converts to `months`, which is used internally.
- Alters the age parsing heuristic to prefer parsing `subject[/session]/scans.tsv`, which is likely to have the most accurate information.
- If found, the age on the first row (scan) will be used.
Also includes a change to avoid using age values without an accompanying sidecar JSON explicitly listing the units.
> ENH: Additional support for age parsing

- nibabies/tests/test_config.py
- nibabies/workflows/base.py
- nibabies/workflows/bold/base.py
Despite adding the 2x2x2 MNIInfant space when generating CIFTI outputs in #381, the file used as the reference image when resampling BOLD -> MNIInfant was hardcoded as 1x1x1. This changes the selection to account for the reference volume resolution, which can change when requesting different grayordinates.
> FIX: Select reference resolution based on grayordinates

- docs/community.md
- docs/conf.py
- docs/faqs.md
- docs/index.md
- docs/installation.md
- docs/outputs.md
- pyproject.toml
Update the RTD to reflect 24.0.0 changes.
Planning on adding a processing pipeline section akin to fmriprep's in a later update. https://fmriprep.org/en/stable/workflows.html
> DOC: First documentation pass

- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/workflows/bold/fit.py
- nibabies/workflows/bold/t2s.py
Adds in method by which to estimate T2*/S0 for multi-echo data, which was already available within the T2* workflow.
> FIX: Add missing me-t2s-fit-method option

- docs/outputs.md
Some missed abbreviation conversions
> docs: reformat abbreviations

- nibabies/interfaces/reports.py
- nibabies/workflows/base.py
Realized when testing that age information is not easily accessible without very verbose logging
> ENH: Add age to session report

- nibabies/cli/parser.py
- nibabies/cli/tests/test_parser.py
- nibabies/workflows/base.py
Previously, `--surface-recon-method auto` would not take into account the presence of a previously computed segmentation when determining MCRIBS as the method, despite the workflow erroring down the line if there is not
one provided.
When working on this, I realized there was not a very clear way to request no surface reconstruction be performed, so this also adds the `none` option to `--surface-recon-method` and deprecates a few ambiguous recon-all specific options (`--force-reconall` and `--fs-no-reconall`)
> FIX: MCRIBS auto surface reconstruction logic

- nibabies/data/reports-spec.yml
This re-adds the missing boilerplate and error reporting to the html report
> FIX: Readd boilerplate, errors to report

- nibabies/config.py
`None` was correctly being set from the parser, but the configuration was not being set since `None`s are skipped.
> FIX: Default surface recon method should be None

- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/workflows/anatomical/fit.py
- nibabies/workflows/anatomical/preproc.py
- nibabies/workflows/anatomical/tests/test_preproc.py
- pyproject.toml
Adds new parser option `--norm-csf`, which will normalize the voxels within the CSF mask (max of either the median value or original value) prior to template registration.
This is experimental and should only be used carefully.
> FEAT: Option to normalize CSF prior to template registration

- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/data/xfm_manifest.json
- nibabies/interfaces/conftest.py
- nibabies/interfaces/patches.py
- nibabies/workflows/anatomical/fit.py
- nibabies/workflows/anatomical/registration.py
- nibabies/workflows/base.py
- nibabies/workflows/tests/test_base.py
- pyproject.toml
- requirements.txt
This PR adds a flag, `--multi-step-reg`, that when enabled alters registrations to `MNI152NLin6Asym` by first registering the anatomical template to `MNIInfant:cohort-X`, and then concatenating that transform in addition to pre-computed ones (`MNIInfant:cohort-X` -> `MNI152NLin6Asym`). If results are promising, other adult templates, such as `MNI152NLin2009cAsym` will follow.
~~ATM, this PR fails to include the precomputed transforms, as they are quite a few (11 MNIInfant cohorts) and `to/from` transforms. I was originally planning on including them in nibabies, but the 3.2GB size is too much.~~
For the time being, the transforms are hosted at an [OSF repository](https://osf.io/y763j/), until they have been finalized and structured for TemplateFlow. We use pooch to fetch the needed …
> ENH: Add flag for multi-step registration to adult templates

- nibabies/interfaces/resampling.py
- nibabies/utils/transforms.py
- nibabies/workflows/bold/registration.py
- pyproject.toml
- requirements.txt
> FIX: Use nitransforms for most xfm handling

- nibabies/workflows/anatomical/fit.py
Closes #422 
- Do not save anatomical preproc that has had CSF normalized (if `--norm-csf` has been enabled)
- Changes `anat_preproc_buffer` to `anat_reg_buffer` to better show its purpose
> FIX: Separate anatomical preproc output from file used for registration

- .circleci/config.yml
Adds a safeguard to avoid polluting `latest` with unofficial releases, while still allowing them to be available on pypi.
> CI: Ensure unofficial releases do not clobber `latest` Docker tag

- nibabies/utils/transforms.py
Fixes #429 
Alter the order when loading a composite transform that includes 2 composite transforms, like is generated if using `--multi-step-reg`. This is required when mapping from the target space to the source voxels.
https://github.com/nipreps/nibabies/blob/6599e40ab39c35e25b1e20e6ec501e21ae8776d4/nibabies/interfaces/resampling.py#L563-L576
It's not clear to me if this is something that needs to be accounted for in nitransforms, or if we should handle this unorthodox case internally here - would love hear any thoughts
> FIX: Reverse transform order for multi-step

- nibabies/interfaces/patches.py
- nibabies/utils/transforms.py
- nibabies/workflows/anatomical/fit.py
- nibabies/workflows/anatomical/registration.py
- nibabies/workflows/base.py
- pyproject.toml
Hopefully the end of this mini-saga - thanks to @tsalo @mattcieslak for taking a look.
Changes included in this:
- Fix ordering in multi-step-reg's anat2std_xfm and std2anat_xfm
- Disassemble transform components in standalone nodes for improved transparency
- Change inputnode fields to reflect intermediate are being used.
- Cache intermediate <-> std transforms to node working directories.
- Add SimpleITK as a dependency for assembling inverse std2anat xfm, until ants CompositeTransformUtil is addressed.
> FIX: Multi-step-reg / composite transform misformation

- nibabies/workflows/base.py
- pyproject.toml
Closes #411 
Pass in new keyword argument added in https://github.com/nipreps/niworkflows/pull/922
> FIX: Lax BIDSDataGrabber anatomical requirement

- nibabies/interfaces/mcribs.py
- nibabies/interfaces/tests/test_mcribs.py
- nibabies/workflows/anatomical/fit.py
- nibabies/workflows/anatomical/surfaces.py
For FreeSurfer / InfantFS, we have passed in the anatomical template - not the preprocessed anatomical - as the input. However, MCRIBS is different, since we are bypassing some of the early preprocessing in the pipeline (conforming, n4, etc). However, due to the intensity clipping, it was reported that the white matter white surface may have been hitting the upper bounds, potentially leading to a decrease in cortical thickness.
This PR restructures the MCRIBS pipeline in the following ways:
- Pass in the anatomical template T2w (a single volume that has gone through DenoiseImage)
- Run N4BiasCorrection prior to MCRIBS injection, making sure to pass in a mask to enable `rescale_intensities` to actually run (it is disabled without a mask present).
> ENH: Minimize clipping prior to surface reconstruction with MCRIBS

- nibabies/workflows/base.py
After comparisons across surface methods (mcribs/infantfs/fs_reconall) on BCP subjects (image below), and revisiting the [MCRIBS paper](https://www.nature.com/articles/s41598-020-61326-2), this PR caps using mcribs as the "recommended" surface reconstruction method to the first 3 months (chronological). 
This only changes a recommendation - users are still available to run any of the surface reconstruction methods for participants of any age (`--surface-recon-method <method>`).
> FIX: Reduce auto recommending MCRIBS after 3 (chronological) months

- nibabies/workflows/anatomical/surfaces.py
Closes #442 
Some affine skewing may occur after `DenoiseImage`, which can cause the t2w mask and template to differ enough to make `N4BiasCorrection` upset. This ensures the mask and template have the same header prior to N4 correction leveraging the mask to localize intensity rescaling.
As of niworkflows 1.12.2, `MatchHeader` will just emit a warning if a significant difference is found - opened https://github.com/nipreps/niworkflows/issues/924 with plans to restrict tolerance in a future release
> FIX: Match mask header prior to n4 correction

- nibabies/workflows/base.py
Add a logger message to show which raw / derivative files have been collected prior to running the workflow.
This message will be enabled using the `--verbose / -v` flag.
> MAINT: Add message to show which files are to be used

- docs/outputs.md
The outputs page on the docs specifies that topup should be identified with the ["B0Identifier"](https://nibabies.readthedocs.io/en/latest/outputs.html#fieldmap-registration) field, when the BIDS spec specifies [the "B0FieldIdentifier" field should be used instead](https://bids-specification.readthedocs.io/en/stable/modality-specific-files/magnetic-resonance-imaging-data.html#using-b0fieldidentifier-metadata)
> DOC: Changed "B0Identifier" -> "B0FieldIdentifier"

- nibabies/workflows/anatomical/apply.py
- nibabies/workflows/anatomical/brain_extraction.py
- nibabies/workflows/anatomical/fit.py
- nibabies/workflows/anatomical/outputs.py
- nibabies/workflows/anatomical/preproc.py
- nibabies/workflows/anatomical/registration.py
- nibabies/workflows/anatomical/resampling.py
- nibabies/workflows/anatomical/segmentation.py
- nibabies/workflows/anatomical/surfaces.py
- pyproject.toml
- requirements.txt
Follows https://github.com/nipreps/smriprep/pull/476
> ENH: Tag anatomical workflows

- nibabies/interfaces/download.py
- nibabies/interfaces/tests/test_download.py
- nibabies/workflows/anatomical/registration.py
Closes https://github.com/nipreps/nibabies/discussions/466 - this allows users to set an environment variable `NIBABIES_POOCH_DIR` to set a custom location to load/save the intermediate template registrations.
Also went ahead and made it an interface rather than an untested function.
> RF: Convert pooch retrieval to interface, allow setting cache dir

- .circleci/config.yml
- .github/workflows/pytest.yml
- env.yml
- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/utils/tests/test_bids.py
- nibabies/workflows/tests/test_base.py
- requirements.txt
- wrapper/src/nibabies_wrapper/__main__.py
Registrations will generally benefit with this enabled, so making it the default.
If only subject -> template registration is required, can disable with `--no-multi-step-reg`.
> ENH: Make `--multi-step-reg` a boolean action, enable by default

- nibabies/cli/parser.py
#472 showed this flag can be more harmful than helpful - now that we add major/minor to the top workflow name, this is no longer needed.
> maint: deprecate `--clean-workdir`

- nibabies/interfaces/resampling.py
Solves issue #471 where the extracted spline grid (in RAS orientation) didn't align with the fieldmap in a different orientation fed into Nibabies. Making this change and rebuilding the Docker image on my own machine removed the error I saw in the issue
> FIX: Orient fieldmap before checking spline fit

- pyproject.toml
* No need to specify `E` and `F` rules with `extend-select`.
* Setting `extend-ignore` has been deprecated. Use plain `ignore` instead.
* Rule `ISC001` is now compatible with `ruff format`.
> MNT: Update ruff configuration
