- .dockerignore
- .gitignore
- Dockerfile
- setup.cfg
- Add prebuilt distribution of FS7 with infant module
- Clean up Dockerfile
> ENH+RF: Dockerfile

- nibabies/cli/parser.py
- nibabies/cli/run.py
- nibabies/cli/workflow.py
- nibabies/config.py
- nibabies/workflows/base.py
- setup.cfg
- Inherit fMRIPrep's parser, making changes where necessary.
- Allow YODA mode for outputs.
> MAINT: Increase alignment with fMRIPrep LTS

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/segmentation.py
- nibabies/workflows/anatomical/surfaces.py
Adds FSL FAST as a fallback option for anatomical segmentation if pre-labeled templates dir is not provided.
> FIX: Segmentation flexibility

- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/segmentation.py
- nibabies/workflows/anatomical/surfaces.py
After an overtly eager merge in #20
> FIX: Incorrect workflow connections

- nibabies/workflows/anatomical/brain_extraction.py
A vital fix for within subject T2->T1 registration
> FIX: Within subject registration

- Dockerfile
- nibabies/interfaces/freesurfer.py
- nibabies/utils/misc.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/surfaces.py
- setup.cfg
With the new dev version, previously calculated segmentations can now be passed into `infant_recon_all`.
> ENH: InfantFS updates

- nibabies/interfaces/freesurfer.py
- nibabies/workflows/anatomical/segmentation.py
> FIX: Infant FS

- nibabies/data/within_subject_t1t2.json
- nibabies/interfaces/nibabel.py
- nibabies/workflows/anatomical/brain_extraction.py
- Adds a dilated brainmask to improve intrasubject anatomical registration
- Updates to a more robust intensity clipping interface
> FIX: Inconsistencies in anatomical coregistration

- nibabies/_warnings.py
To actually allow disabling warnings:
https://github.com/nipreps/nibabies/blob/c607811c719cc8e9fed03f9b748cd17818452ddb/nibabies/config.py#L102-L109
> FIX: Add warnings handler

- CHANGES.md
- Dockerfile
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/bold/confounds.py
- nibabies/workflows/bold/resampling.py
- scripts/fetch_templates.py
Functional workflow is now usable.
Final clean ups include:
- better tracking of templates within Docker container
- remove high memory requirements on certain confound nodes
> REL: 0.0.3

- nibabies/config.py
- nibabies/workflows/base.py
- nibabies/workflows/bold/base.py
Closes #42 
This may serve as the blueprint for the next minor release of fMRIPrep.
> ENH: Add susceptibly distortion correction

- nibabies/interfaces/conftest.py
- nibabies/interfaces/workbench.py
Closes #49
These should all eventually just be upstreamed to Nipype directly.
> ENH: Finalize missing workbench commands

- nibabies/workflows/bold/base.py
> FIX: Remove duplicate connection

- setup.cfg
> MAINT: Fix development packages to releases

- wrapper/README.rst
- wrapper/nibabies_wrapper.py
- wrapper/setup.cfg
- wrapper/setup.py
This takes inspiration from fMRIPrep's ``fmriprep-docker`` wrapper,
but with the added benefit of supporting Singularity as well.
> ENH: Add wrapper package to simplify usage

- Dockerfile
- nibabies/utils/bids.py
Closes #73, #77
Since testing was exclusively using ``--skip-bids-validation``...
> FIX: Add BIDS validation

- Dockerfile
Inspired from nipreps/fmriprep@2adcdaedb8b82b2762e2f753b95d14d3dac766c4
> ENH: Modernize Dockerfile

- nibabies/workflows/bold/registration.py
Porting over fix originally implemented in nipreps/fmriprep#2444
> FIX: Feed NiTransforms with LTAs of type RAS2RAS

- Dockerfile
- Add and generate proper locales
- Dev install nibabies
> FIX: Small Docker environment fixes

- nibabies/workflows/bold/registration.py
After porting over nipreps/fmriprep#2444, we started running into:
```
Node: nibabies_wf.single_subject_01_wf.func_preproc_ses_1mo_task_rest_acq_PA_run_001_wf.bold_reg_wf.bbreg_wf.bbregister
Working directory: /work/nibabies_wf/single_subject_01_wf/func_preproc_ses_1mo_task_rest_acq_PA_run_001_wf/bold_reg_wf/bbreg_wf/bbregister
Node inputs:
args = <undefined>
compress_report = auto
contrast_type = t2
dof = 6
environ = {}
epi_mask = <undefined>
fsldof = <undefined>
init = <undefined>
init_cost_file = <undefined>
init_reg_file = /work/nibabies_wf/single_subject_01_wf/func_preproc_ses_1mo_task_rest_acq_PA_run_001_wf/bold_reg_wf/bbreg_wf/mri_coreg/registration.lta
intermediate_file = <undefined>
out_fsl_file = <undefined>
out_lta_file = True
out_reg_file = <undefined>
out_report = report.svg …
```
> FIX: Avoid running BBReg under certain conditions

- nibabies/workflows/base.py
- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/resampling.py
- setup.cfg
Ensure distortion fieldwarp is applied to the bold series.
Upstreams changes in nipreps/fmriprep#2392
> FIX: SDC fieldwarp application

- nibabies/interfaces/freesurfer.py
If the working directory was not present, `infant_recon_all` (IRA) would be called again (though with some checkpointing)
This adds a check querying the output directory for a summary log file, which includes a line if IRA finished completely, and skips the call altogether.
Depending on updates to IRA, this may have to be revisited.
> ENH: Do not run infant_recon_all if already completed

- Dockerfile
Following nipreps/fmriprep#2551
> DOCKER: Reduce image size

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Removes unnecessary contact field
- Require interest on feature requests, add additional info field.
> MAINT: Update issue forms

- docs/conf.py
- docs/installation.md
- docs/usage.md
wishlist: substitutions within code-blocks
> DOC: Use dynamic versioning within docs

- Dockerfile
- nibabies/data/flirtsch/bbr.sch
- nibabies/data/itkIdentityTransform.txt
- scripts/fetch_templates.py
- setup.cfg
- wrapper/nibabies_wrapper.py
One fix uncovered the other, so I'm just including the aggregate here.
- Preload neonate MNIInfant templates.
- Updates git-annex version
- Ensure required data files are packaged
- Clean up wrapper behavior
> MAINT: Address various pain points

- nibabies/cli/parser.py
> FIX: Check if segmentation directory exists

- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/outputs.py
- nibabies/workflows/bold/stc.py
@mgxd Trying to do this as a set of coherent commits. Any ones that you're happy with can be cherry-picked onto master to reduce the eventual diff.
I'm trying to remove quote-only changes, but some are slipping through.
> ENH: Update to fMRIPrep 21.0.0rc2, including ME derivatives

- docs/requirements.txt
- nibabies/workflows/bold/confounds.py
- setup.cfg
> FIX: ICA Aroma

- nibabies/cli/parser.py
- nibabies/config.py
> ENH: Add --me-output-echos CLI flag

- .readthedocs.yml
> MAINT: Add RTD config

- wrapper/nibabies_wrapper.py
- Displaying help should return 0 exit code
- Remove dual `--help`/`--version` behavior - only show wrapper options.
> RF: Polish wrapper logic

- nibabies/utils/bids.py
- nibabies/utils/validation.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/brain_extraction.py
Continues #173 after testing with @madisoth's test case
> ENH: Validate files passed with `--derivatives`

- .circleci/config.yml
- .dockerignore
- Dockerfile
Hopefully addresses #142 ...
cc @effigies for another pair of eyes
> FIX: Ensure version is written to version file

- Dockerfile
- Remove failing multiarch download (AFNI)
- Purge version from FSL directory
- Use conda env from official nipreps miniconda image
> MAINT: Dockerfile

- README.md
- setup.cfg
This is to improve the metadata on https://pypi.org/project/nibabies/
> MAINT: Update package metadata

- Dockerfile
- nibabies/cli/parser.py
- nibabies/config.py
- nibabies/workflows/anatomical/base.py
- nibabies/workflows/anatomical/surfaces.py
- nibabies/workflows/base.py
- nibabies/workflows/bold/base.py
> ENH: Add option to use `recon-all` instead of `infant_recon_all`

- .circleci/config.yml
- Dockerfile
- nibabies/cli/run.py
- nibabies/config.py
- nibabies/utils/misc.py
- setup.cfg
Incorporate https://github.com/mgxd/migas to fetch usage, telemetry information.
> ENH: Add migas telemetry to nibabies

- nibabies/cli/run.py
- nibabies/utils/misc.py
- nibabies/utils/telemetry.py
Incorporates `migas` 0.2.0 API - while cleaning up the implementation a bit.
> RF: migas updates

- Dockerfile
> FIX: Add missing shared object for `infant_recon_all`

- nibabies/workflows/bold/base.py
Closes #232 
@madisoth can you patch this branch of nibabies into your container and verify the multi-echo correction is now working?
> FIX: Field name for multi-echo fieldmap correction

- README.md
- docs/community.md
- docs/index.md
> DOC: Advertise nipreps community pages, add section on contributions

- .circleci/config.yml
- nibabies/workflows/bold/base.py
- scripts/check_outputs.py
> FIX: Use the binarized output from the brain extraction

- .circleci/bcp_full_outputs.txt
- nibabies/interfaces/maths.py
- nibabies/interfaces/reports.py
- nibabies/workflows/bold/base.py
- nibabies/workflows/bold/outputs.py
- nibabies/workflows/bold/resampling.py
- nibabies/workflows/bold/t2s.py
This ports the relevant pieces from fMRIPrep to generate T2star outputs in the desired output spaces.
> ENH: Output T2star maps for multiecho data

- setup.cfg
In preparation for 22.2.0 release.
> DEP: Pin sdcflows to minor series

- nibabies/config.py
Porting over https://github.com/nipreps/fmriprep/pull/2985
> FIX: Estimate free memory with available, not free

- Dockerfile
> DKR: Add bc for FreeSurfer recons

- docs/faqs.md
> DOC: Update `--derivatives` FAQ

- CHANGES.md
- requirements.txt
Remaining items for 24.0.0 release.
- Documentation
- Circle smoke test
> REL: 24.0.0rc0

- Dockerfile
- nibabies/config.py
This address the discussion in #352 - has come up while testing #395 as well.
First, let's see how noisy it is without any filtering.
> MAINT: Revisit warnings filter

- nibabies/utils/bids.py
Change index_val to index_value in a couple of places to match the keyword argument of _get_age_from_tsv()
> FIX Update bids.py

- nibabies/cli/parser.py
- nibabies/cli/tests/test_parser.py
- nibabies/conftest.py
Starting the code coverage ascension
> MAINT: Port over parser and tests from fmriprep

- nibabies/workflows/anatomical/resampling.py
- pyproject.toml
Sorry about that. I changed that this morning and forgot that it could have impact outside sdcflows itself.
> fix: Support sdcflows@main and smriprep >=0.18

- env.yml
> FIX/DOCKER: Add Convert3d

- CHANGES.md
- pyproject.toml
- requirements.txt
Preparing for a new release, slated for Monday May 19
@joey-scanga would you like to be added to the project [contributors](https://github.com/nipreps/nibabies/blob/master/.maint/contributors.json)? If so, can you open a PR adding your info, or let me know and I can add it?
> REL: 25.0.2
